### ISSUE TITLE
Group keyboard navigation should ignore non-radio-button children

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-radio-button#115] opened 2019-07-02 13:28 UTC
Currently, if you place elements next to radio buttons in a group, they are involved in "roving tab index" navigation (with arrow keys)

![radio-group-issue](https://user-images.githubusercontent.com/1222264/60516381-4f65e600-9ce6-11e9-90fc-8553951795f3.gif)

Related to #56

**Comment by web-padawan** [comment] 2020-02-14 13:13
Closing as duplicate of #56 which is now marked as a bug (and not an enhancement).

**Closed by web-padawan** 2020-02-14 13:13 UTC
